/var/log/ansible-pull.log {
    daily
    rotate 15
    compress
    delaycompress
    missingok
    notifempty
    maxsize 50M
    create 0644 root root
}

/home/orangepi/screen-manager/logs/*.log {
    daily
    rotate 15
    compress
    delaycompress
    missingok
    notifempty
    maxsize 50M
    create 0644 orangepi orangepi
    copytruncate
}