---
- name: Create ansible-pull log file
  copy:
    content: ""
    dest: /var/log/ansible-pull.log
    owner: root
    group: root
    mode: '0644'
    force: no

- name: Deploy update wrapper script
  copy:
    src: orion-update.sh
    dest: /usr/local/bin/orion-update.sh
    owner: root
    mode: '0755'

- name: Ensure ansible-pull cronjob is installed
  cron:
    name: "Orion auto-update"
    user: root
    job: "/usr/local/bin/orion-update.sh"
    hour: 1
    minute: 0