---
- name: Ensure ansible-pull cronjob is installed
  cron:
    name: "Orion auto-update"
    user: root
    job: "ansible-pull -U https://github.com/ORION-DEVELOPMENT-DIONE/update-manager.git -C main local.yml -i localhost, -o >> /var/log/ansible-pull.log 2>&1"
    hour: 0
    minute: 0

- name: Create ansible-pull log file
  copy:
    content: ""
    dest: /var/log/ansible-pull.log
    owner: root
    group: root
    mode: '0644'
    force: no
